version: '3'

networks:
  backend:
    driver: bridge

services:

  sqlserver2017:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Secret1234
    volumes:
      - '~/.envdocker/data/mssql:/var/opt/mssql'
    networks:
      - backend

  net-core:
    image: net-core
    build:
      context: .
    depends_on:
      - sqlserver2017
    ports:
      - "10000:80"
    networks:
      - backend